package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "example",
    srcs = ["example.cc"],
    linkstatic = True,
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//phtree:phtree",
    ],
)

